[settings]
# Python 版本（用于匹配 packages 中的嵌入式 Python 压缩包）
VERSION=3.13.2
# 虚拟环境名称
VENV_NAME=venvName
# 是否升级 pip（yes / no）
UPGRADE_PIP=yes
# 是否自动安装 Node.js（yes / no）
AUTO_INSTALL_NodeJs=yes
# 默认 Python 执行命令
DefaultExecution=python main.py